version: '2'
services:
  mssql-db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - SA_PASSWORD=1Secure*Password1
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    command: /bin/sh -c "(/opt/mssql/bin/sqlservr &) && sleep 30s && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 1Secure*Password1 -d master -Q 'CREATE DATABASE [RewardsSystem]' && sleep infinity"

  api-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql-db;Database=RewardsSystem;User=sa;Password=1Secure*Password1;
    build:
      context: .
      dockerfile: api/RewardsSystem.API/Dockerfile
    depends_on:
      - mssql-db
    ports:
      - 44381:80
volumes:
  mssql_db_volume: {}
